
FROM maven:3-openjdk-17 AS build
WORKDIR /app

COPY . .

FROM openjdk:17-jdk-slim
WORKDIR /app

COPY --from=build /app/target/DrComputer-0.0.1-SNAPSHOT.war drcomputer.war
EXPOSE 8080

ENTRYPOINT ["java","-jar","drcomputer.war"]

#RUN mvn clean package -DskipTests
#FROM ubuntu:latest
#LABEL authors="Cao"
#
#ENTRYPOINT ["top", "-b"]